application: AtomNet
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: www/menu/index.html
  upload: www/menu/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

